-- Mock events for development
insert into events (title, description, start_date, end_date, location, image_url, price, url, notes, status)
values
('Funky Friday Kickoff', 'Start your weekend with a high-energy funk band and a crowd ready to dance. Enjoy signature cocktails and a lively atmosphere as the citys best musicians take the stage. Doors open at 8pm, music starts at 9pm.', '2025-05-02T20:00:00Z', null, 'Four Quarter Bar', '/images/events/1745652916473-cropped-fq_piano.jpg', '10', null, 'Artist: The Groove Collective — A 7-piece funk powerhouse known for their electrifying live shows and tight horn section.', 'published'),
('Soulful Saturday', 'Immerse yourself in soulful vocals and smooth instrumentals. Our featured artist brings a blend of classic soul and modern R&B, perfect for a night out with friends.', '2025-05-03T21:00:00Z', null, 'Four Quarter Bar', '/images/events/1745652916473-cropped-fq_piano.jpg', '12', null, 'Artist: Jasmine Ray — Award-winning vocalist with a voice that captivates and inspires.', 'published'),
('Indie Rock Night', 'Discover the best of the indie scene with three up-and-coming bands. Expect original music, creative covers, and a crowd of passionate fans.', '2025-05-09T20:00:00Z', null, 'Four Quarter Bar', '/images/events/1745652916473-cropped-fq_piano.jpg', '15', null, 'Artists: The Wild Pines, Static Avenue, and Luna Drive — Each bringing their unique sound to the stage.', 'published'),
('Jazz & Cocktails', 'A sophisticated evening of jazz standards and improvisation. Enjoy candlelit tables, a curated cocktail menu, and the smooth sounds of saxophone and piano.', '2025-05-10T21:00:00Z', null, 'Four Quarter Bar', '/images/events/1745652916473-cropped-fq_piano.jpg', '10', null, 'Artist: The Blue Note Quartet — Local jazz legends with decades of experience.', 'published'),
('Reggae Vibes', 'Feel the rhythm of the islands with live reggae and Caribbean-inspired drinks. The dance floor will be open all night!', '2025-05-16T20:00:00Z', null, 'Four Quarter Bar', '/images/events/1745652916473-cropped-fq_piano.jpg', '15', null, 'Artist: Irie Heights — Bringing authentic reggae grooves and positive energy.', 'published'),
('Latin Dance Party', 'Salsa, bachata, and merengue all night long! Dance instructors will be on hand to get everyone moving, no partner required.', '2025-05-17T21:00:00Z', null, 'Four Quarter Bar', '/images/events/1745652916473-cropped-fq_piano.jpg', '12', null, 'Artist: Sonido Caliente — A dynamic Latin band with infectious rhythms.', 'published'),
('Open Mic Showcase', 'Step up to the mic or cheer on local talent at our open mic night. All genres and skill levels welcome. Sign-ups start at 7pm.', '2025-05-23T20:00:00Z', null, 'Four Quarter Bar', '/images/events/1745652916473-cropped-fq_piano.jpg', '0', null, 'Host: DJ Harmony — Keeping the energy high and the show running smooth.', 'published'),
('Blues & BBQ', 'Enjoy a night of classic blues and mouthwatering BBQ specials. Our featured artist brings the soul of the Delta to the stage.', '2025-05-24T21:00:00Z', null, 'Four Quarter Bar', '/images/events/1745652916473-cropped-fq_piano.jpg', '15', null, 'Artist: Big Sam Rivers — Renowned blues guitarist and storyteller.', 'published'),
('Rock Revival', 'A tribute to classic rock anthems and deep cuts. Sing along to your favorites and discover new classics.', '2025-05-30T20:00:00Z', null, 'Four Quarter Bar', '/images/events/1745652916473-cropped-fq_piano.jpg', '10', null, 'Artist: The Revivalists — High-energy rockers with a passion for the classics.', 'published'),
('Saturday Headliners', 'National touring acts and local favorites share the stage for an unforgettable night. VIP packages available.', '2025-05-31T21:00:00Z', null, 'Four Quarter Bar', '/images/events/1745652916473-cropped-fq_piano.jpg', '20', null, 'Artists: The Main Event Band — Known for their explosive live performances.', 'published'),
('Acoustic Friday', 'Unplug and unwind with acoustic sets from some of the area\'s best singer-songwriters. Perfect for a laid-back evening.', '2025-06-06T20:00:00Z', null, 'Four Quarter Bar', '/images/events/1745652916473-cropped-fq_piano.jpg', '8', null, 'Artists: Sarah Lane & Friends — Heartfelt lyrics and beautiful melodies.', 'published'),
('Summer Jam Finale', 'Celebrate the start of summer with a festival-style lineup, food trucks, and drink specials. Music on two stages all night long!', '2025-06-07T21:00:00Z', null, 'Four Quarter Bar', '/images/events/1745652916473-cropped-fq_piano.jpg', '18', null, 'Artists: The Summer Collective — A supergroup of local talent.', 'published');
