import { Event } from "@/types/event"

// Featured events shown at the top of the events page
export const featuredEvents: Event[] = [
  {
    id: "1",
    title: "Saturday Night Live: The Rock Experience",
    slug: "saturday-night-live-rock-experience",
    description: "Join us for an unforgettable rock experience featuring three local bands playing classic and modern rock hits. Full bar service and food available.",
    date: "2023-05-20",
    startTime: "20:00",
    endTime: "01:00",
    location: "Main Stage",
    coverImage: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?q=80&w=1170&auto=format&fit=crop",
    isPublished: true,
    price: "$15",
    performerName: "Various Artists",
    performerDescription: "Local rock bands bringing you the best of classic and modern rock.",
    ticketUrl: "https://tickets.example.com/event1",
    socialShareEnabled: true,
    createdAt: "2023-04-01",
    updatedAt: "2023-04-05",
  },
  {
    id: "2",
    title: "Jazz & Blues Festival",
    slug: "jazz-blues-festival",
    description: "A night celebrating the rich traditions of jazz and blues music with renowned local artists and special guests.",
    date: "2023-05-27",
    startTime: "19:00",
    endTime: "23:30",
    location: "Main Stage",
    coverImage: "https://images.unsplash.com/photo-1511192336575-5a79af67a629?q=80&w=1170&auto=format&fit=crop",
    isPublished: true,
    price: "$20",
    performerName: "The Blue Note Ensemble",
    performerDescription: "Award-winning jazz collective bringing smooth sounds and soulful blues.",
    ticketUrl: "https://tickets.example.com/event2",
    socialShareEnabled: true,
    createdAt: "2023-04-02",
    updatedAt: "2023-04-06",
  },
]

// Regular upcoming events
export const upcomingEvents: Event[] = [
  {
    id: "3",
    title: "Acoustic Open Mic Night",
    slug: "acoustic-open-mic-night",
    description: "Showcase your talent at our weekly open mic night. All acoustic performers welcome.",
    date: "2023-05-15",
    startTime: "19:30",
    endTime: "22:30",
    location: "Bar Area",
    coverImage: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=1074&auto=format&fit=crop",
    isPublished: true,
    price: "Free Entry",
    performerName: "Various Artists",
    performerDescription: "Local talent and you!",
    ticketUrl: null,
    socialShareEnabled: true,
    createdAt: "2023-04-03",
    updatedAt: "2023-04-07",
  },
  {
    id: "4",
    title: "Electronic Music Showcase",
    slug: "electronic-music-showcase",
    description: "Experience cutting-edge electronic music with live performances and DJ sets.",
    date: "2023-06-03",
    startTime: "21:00",
    endTime: "02:00",
    location: "Main Stage",
    coverImage: "https://images.unsplash.com/photo-1501612780327-45045538702b?q=80&w=1170&auto=format&fit=crop",
    isPublished: true,
    price: "$18",
    performerName: "Digital Pulse",
    performerDescription: "Innovative electronic artists pushing the boundaries of sound.",
    ticketUrl: "https://tickets.example.com/event4",
    socialShareEnabled: true,
    createdAt: "2023-04-04",
    updatedAt: "2023-04-08",
  },
  {
    id: "5",
    title: "Country & Western Night",
    slug: "country-western-night",
    description: "Put on your boots for a night of country and western music, line dancing, and southern hospitality.",
    date: "2023-06-10",
    startTime: "20:00",
    endTime: "00:00",
    location: "Main Stage",
    coverImage: "https://images.unsplash.com/photo-1558898479-33c0057a5d12?q=80&w=1170&auto=format&fit=crop",
    isPublished: true,
    price: "$12",
    performerName: "Prairie Wind",
    performerDescription: "Authentic country sounds from the heart of the Midwest.",
    ticketUrl: "https://tickets.example.com/event5",
    socialShareEnabled: true,
    createdAt: "2023-04-05",
    updatedAt: "2023-04-09",
  },
  {
    id: "6",
    title: "Indie Band Showcase",
    slug: "indie-band-showcase",
    description: "Discover the best up-and-coming indie bands in our monthly showcase event.",
    date: "2023-06-17",
    startTime: "19:00",
    endTime: "23:00",
    location: "Main Stage",
    coverImage: "https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?q=80&w=1170&auto=format&fit=crop",
    isPublished: true,
    price: "$10",
    performerName: "Various Artists",
    performerDescription: "A curated selection of the best emerging indie talent.",
    ticketUrl: "https://tickets.example.com/event6",
    socialShareEnabled: true,
    createdAt: "2023-04-06",
    updatedAt: "2023-04-10",
  },
  {
    id: "7",
    title: "Retro 80s Dance Party",
    slug: "retro-80s-dance-party",
    description: "Travel back in time with our 80s-themed dance party featuring the biggest hits from the decade.",
    date: "2023-06-24",
    startTime: "21:00",
    endTime: "02:00",
    location: "Main Floor",
    coverImage: "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?q=80&w=1170&auto=format&fit=crop",
    isPublished: true,
    price: "$15",
    performerName: "DJ Flashback",
    performerDescription: "Specializing in the best dance tracks from the 1980s.",
    ticketUrl: "https://tickets.example.com/event7",
    socialShareEnabled: true,
    createdAt: "2023-04-07",
    updatedAt: "2023-04-11",
  },
  {
    id: "8",
    title: "Summer Solstice Celebration",
    slug: "summer-solstice-celebration",
    description: "Celebrate the longest day of the year with live music, special cocktails, and summer vibes.",
    date: "2023-06-21",
    startTime: "18:00",
    endTime: "23:59",
    location: "Entire Venue",
    coverImage: "https://images.unsplash.com/photo-1506157786151-b8491531f063?q=80&w=1170&auto=format&fit=crop",
    isPublished: true,
    price: "$20",
    performerName: "Various Artists",
    performerDescription: "A lineup of diverse performers to celebrate summer.",
    ticketUrl: "https://tickets.example.com/event8",
    socialShareEnabled: true,
    createdAt: "2023-04-08",
    updatedAt: "2023-04-12",
  },
]

// Combine all events for calendar view
export const allEvents = [...featuredEvents, ...upcomingEvents] 